language: php

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

php:
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=6.*
  - LARAVEL_VERSION=7.*
# matrix:
#   exclude:
#     - php: 7.1
#       env: LARAVEL_VERSION=6.*

sudo: false

before_install:
  - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update
  - composer require "illuminate/filesystem:${LARAVEL_VERSION}" --no-update

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: never