language: php

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

php:
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.*
matrix:
  exclude:
    - php: 7.1
      env: LARAVEL_VERSION=6.*

sudo: false

before_install:
  - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update
  - composer require "illuminate/filesystem:${LARAVEL_VERSION}" --no-update

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: never