language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

sudo: false

install:
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: never